
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIBASHIS SAHU
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    String imagePth=null;
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelMin1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelCreateAcc = new javax.swing.JLabel();
        jTextFieldlname = new javax.swing.JTextField();
        jTextFielduname = new javax.swing.JTextField();
        jTextFieldfname = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelPic = new javax.swing.JLabel();
        jButtoncreatre = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(640, 20, 20, 29);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(586, 20, 30, 29);

        jLabelMin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin1.setText("Create New Account");
        jLabelMin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Last Name:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 100, 149, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("User Name:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 170, 149, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Password:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 240, 149, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Picture:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 380, 149, 32);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("First Name:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(48, 39, 149, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Retype Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 310, 149, 32);

        jLabelCreateAcc.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCreateAcc.setText("Already have an account? Click Here To Login.");
        jLabelCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateAccMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelCreateAcc);
        jLabelCreateAcc.setBounds(240, 630, 220, 30);

        jTextFieldlname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jTextFieldlname);
        jTextFieldlname.setBounds(200, 100, 340, 30);

        jTextFielduname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jTextFielduname);
        jTextFielduname.setBounds(200, 170, 340, 30);

        jTextFieldfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(jTextFieldfname);
        jTextFieldfname.setBounds(200, 40, 340, 30);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBrowse);
        jButtonBrowse.setBounds(460, 390, 75, 25);

        jButtonCancel.setBackground(new java.awt.Color(242, 38, 19));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);
        jButtonCancel.setBounds(200, 590, 100, 30);

        jLabelPic.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPic.setOpaque(true);
        jPanel3.add(jLabelPic);
        jLabelPic.setBounds(200, 390, 220, 170);

        jButtoncreatre.setBackground(new java.awt.Color(30, 139, 135));
        jButtoncreatre.setText("Creat");
        jButtoncreatre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtoncreatre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncreatreActionPerformed(evt);
            }
        });
        jPanel3.add(jButtoncreatre);
        jButtoncreatre.setBounds(380, 590, 90, 30);
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(200, 240, 340, 30);
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(200, 310, 340, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelMin1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateAccMouseClicked
        // TODO add your handling code here:
        login logf=new login();
        logf.setVisible(true);
        logf.pack();
        logf.setLocationRelativeTo(null);
        logf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelCreateAccMouseClicked
    
    public boolean isUserNameExist(String un){
        boolean uExist= false;
        Connection con=myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
       
        try {
            ps=con.prepareStatement("SELECT * FROM `user` WHERE `unn` = ? ");
            ps.setString(1,jTextFielduname.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                uExist=true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return uExist;
    }
            
    
    
    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
          myfunc mf=new myfunc();
          imagePth =mf.browseImage(jLabelPic);
        
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    public boolean verifyData(){
        if(jTextFieldfname.getText().equals("") && jTextFieldlname.getText().equals("") 
           || jTextFielduname.getText().equals("")
                || String.valueOf(jPasswordField1.getPassword()).equals("") )
           {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!!");
            return false;
        }else if(!String.valueOf(jPasswordField1.getPassword()).equals(String.valueOf(jPasswordField2.getPassword()))){
            
            JOptionPane.showMessageDialog(null, "Passwords are not same!!!!");
            return false;}
        else if(imagePth==null){
            JOptionPane.showMessageDialog(null, " Image not selected!!");
            return false;}
        else 
            return true;
    } 
    
    private void jButtoncreatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncreatreActionPerformed
        if ( verifyData()){
           Connection con=myConnection.getConnection();
           PreparedStatement ps;
        try {
            ps=con.prepareStatement("INSERT INTO `user`(`fnn`, `lnn`, `unn`, `pssn`, `pccn`) VALUES (?,?,?,?,?)");
            ps.setString(1,jTextFieldfname.getText());
            ps.setString(2,jTextFieldlname.getText());
            ps.setString(3,jTextFielduname.getText());
            ps.setString(4,String.valueOf(jPasswordField1.getPassword()));
            
            InputStream img=new FileInputStream(new File(imagePth));
            ps.setBlob(5, img);
            
            if(isUserNameExist(jTextFielduname.getText())){
                JOptionPane.showMessageDialog(null, "User Name Already Exist.");
            }
            else{
                if(ps.executeUpdate()!=0){
                JOptionPane.showMessageDialog(null, "Account Created Seccesfully.");
            }else{
                JOptionPane.showMessageDialog(null, "Something Wrong!");
            }
            }
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
        
        
    }//GEN-LAST:event_jButtoncreatreActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtoncreatre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCreateAcc;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelMin1;
    private javax.swing.JLabel jLabelPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldlname;
    private javax.swing.JTextField jTextFielduname;
    // End of variables declaration//GEN-END:variables
}
